### ISSUE TITLE
Where is the TIGER

### ISSUE THREAD

**Issue by nise** [ooz/Confopy#1]
Could provide some more details on how to install TIGER?

First of all most users do not know how to find out the install location. On ubuntu it should be '/user/local/lib/python<YOUR-VERSION-HERE>'/dist-packages/confopy

Then there is no file called  tiger_dl_patch.py

Finally, the provided script run into errors. 

> python  tiger_release_aug07.corrected.16012013_patch.py
> Traceback (most recent call last):
>   File "tiger_release_aug07.corrected.16012013_patch.py", line 70, in <module>
>     main()
>   File "tiger_release_aug07.corrected.16012013_patch.py", line 24, in main
>     convert_to_utf8()
>   File "tiger_release_aug07.corrected.16012013_patch.py", line 33, in convert_to_utf8
>     with codecs.open(TIGER_FILE, "r", SOURCE_ENC) as sourceFile:
>   File "/usr/lib/python2.7/codecs.py", line 878, in open
>     file = **builtin**.open(filename, mode, buffering)
> IOError: [Errno 2] No such file or directory: 'tiger_release_aug07.corrected.16012013.xml'

Thank you for providing some help!

**Comment by ooz** [comment]
Confopy should tell you where it expects the corpus file, when you try to execute a report. E.g.:

```
olli@cube:~/venv-confopy$ bin/confopy -r document paper.pdf
Error: TIGER corpus file not found. Please follow README to download and place it properly.
       (A file named tiger_release_aug07.corrected.16012013_utf8_patched.xml
        needs to be placed here: /home/olli/venv-confopy/lib/python2.7/site-packages/confopy/localization/de/corpus_de)
```

I can't reproduce the issue in Ubuntu 16.04 with Python 2.7.12. I installed Confopy using a `virtualenv` (recommended in general if you want to evaluate certain Python software):

```
sudo apt install virtualenv
virtualenv venv-confopy
cd venv-confopy/
bin/pip install confopy
```

Then I tried to execute a report on a paper. I got the message listed above. Change to the directory mentioned in the error message:

```
cd /home/olli/venv-confopy/lib/python2.7/site-packages/confopy/localization/de/corpus_de
```

Execute the download+patch script:

```
python tiger_dl_patch.py
```
